config/routes.rb
FragmentCachingDemoapp::Application.routes.draw do

  root :to => 'articles#index'  
  resources :articles do
    resources :comments
  end
  
end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments

  validates :title, :content, :presence => true
  
  
  def to_param
    "#{id}-#{title.gsub(/[\s]+/, '-')}"
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :article, :touch => true
  
  validates :article_id, :body, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new params.require(:article).permit(:title, :content)
    if @article.save
      redirect_to articles_path, :notice => "Article has been created successfully"
    else
      render :action => :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes params.require(:article).permit(:title, :content)
       redirect_to [:articles]
    else
      render :action => :edit
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build params[:comment].permit(:body)
      if @comment.save
        render :json => { :notice => "Comment Has Been Created Successfully", :html => html_formatted_comment }
      else
        logger.info @comment.errors.inspect
        render :json => @comment.errors, :status => 401
      end
  end



  private

  def html_formatted_comment
    ("<div class='comment'>" << "#{ @comment.id.to_s } - "  "#{ @comment.body }" << "</div>").html_safe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_comment.html.erb
<div class='comment'>
 <%=comment.id%>-<%=comment.body%>
</div>

app/views/articles/edit.html.erb
<div class='page-template container'>
  <h2>Create Article</h2>
  <div class='form'>
    <%= form_for @article do |form|%>
        <div class='field'>
            <label for="Title">Title</label>
            <%=form.text_field :title%>
            <span class='error'><%=@article.errors["title"].first%></span>
        </div>
        <div class='field'>
           <label for="Content">Content</label>
            <%=form.text_area :content, :cols => 49, :rows => 10%>
           <span class='error'><%=@article.errors["content"].first%></span>
        </div>
        <%=form.submit "Save"%>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<% cache  @articles do %>
<div class='page-template'>
  <h2 style='margin-bottom: 10px;'>Listing Articles</h2>
  <h3 style='margin-bottom: 10px;'><a href="<%=new_article_path%>">Create Article</a></h3>
  <div class='articles'>
    <% @articles.each do |article|%>      
        <div class='article'>
           <div class='title'>
             <%=link_to article.title, article%>
           </div>
           <div>
             <%=article.content%>
           </div>
        </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/articles/new.html.erb
<div class='page-template container'>
  <h2>Create Article</h2>
  <div class='form'>
    <%= form_for @article do |form|%>
        <div class='field'>
            <label for="Title">Title</label>
            <%=form.text_field :title%>
            <span class='error'><%=@article.errors["title"].first%></span>
        </div>
        <div class='field'>
           <label for="Content">Content</label>
            <%=form.text_area :content, :cols => 49, :rows => 10%>
           <span class='error'><%=@article.errors["content"].first%></span>
        </div>
        <%=form.submit "Save"%>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class='page-template'>
  <%=link_to "All Articles", [:articles], :style => "float:right"%>
  <% cache @article  do %>

     <div class='article-show'>
        <h1><%=@article.title%></h1>
        <h2><a href="<%=edit_article_path%>">Edit</a></h2>
        <%=@article.content%>
     </div>

    <div class='comments'>
      <h3>All Comments</h3>
      <div id='article_comments' style=''>
        <%=render :partial => 'comment', :collection => @article.comments%>
      </div>

    </div>

   <% end %>
  <div class='form'>
    <%=form_for (@comment||=@article.comments.build), :url => article_comments_path(@article), :remote => true do |form|%>
        <div class='field'>
          <%=form.text_area :body, :cols => 40, :rows => 4 %>
        </div>
        <%=form.submit "Save", :class => 'submit-button'%>
    <% end %>
  </div>

</div>

<script type="text/javascript">
  var comment_form = new AjaxErrorRepresenter('comment', { form_id:'new_comment', update_container: 'article_comments' });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FragmentCachingDemoapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
<%= yield %>
</div>
</body>
</html>